id = "statamic-antlers-toolbox"
name = "Statamic Antlers Toolbox"
version = "1.0.0"
schema_version = 1
authors = ["Eugene Karuna <hello@littlehatdesign.com>"]
description = "Enhanced syntax highlighting and language server support for Statamic Antlers templates. Fork of statamic-antlers by Joachim RÃ¼tter (mynetx)."
repository = "https://github.com/eugene-karuna/zed-statamic-antlers"

[grammars.antlers]
repository = "https://github.com/eugene-karuna/tree-sitter-antlers"
commit = "a5a592b"

[language_servers.vscode-antlers-language-server]
name = "Statamic Antlers Language Server"
language = "Statamic Antlers"
